sudo: required
services:
  - docker

before_install:
  - docker build -t fredyball/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run fredyball/react-test npm test -- --coverage

after_success:
  - docker build -t fredyball/multi-client ./client
  - docker build -t fredyball/multi-nginx ./nginx
  - docker build -t fredyball/multi-server ./server
  - docker build -t fredyball/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push fredyball/multi-client
  - docker push fredyball/multi-nginx
  - docker push fredyball/multi-server
  - docker push fredyball/multi-worker
